{% set name = "cassandra" %}
{% set version = "1.2.5" %}
{% set sha256 = "8cff9277560ebccd3ce78291ec8c2bddb8248174b5b804a6ba18cc67b45aede5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MaginnGroup/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - make
  host:
    - {{ compiler('fortran') }}
    - python
    - pip
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  run:
    - python
    - future
    - numpy

test:
  commands:
    - cassandra.exe -h
    - mcfgen.py -h
    - library_setup.py -h

about:
  home: https://github.com/MaginnGroup/Cassandra
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'Open source atomistic Monte Carlo software package'
  description: |
    Cassandra is an atomistic Monte Carlo software package developed by
    the Maginn Group at the University of Notre Dame.
    The core code is written in Fortran, but the package also includes a few
    Python scripts to help with simulation setup. Complete documentation,
    workshop materials, and a user forum can be found at cassandra.nd.edu.
  doc_url: https://cassandra.nd.edu/
  dev_url: https://github.com/MaginnGroup/Cassandra

extra:
  recipe-maintainers:
    - rsdefever
