travis:
  secure:
    BINSTAR_TOKEN: GzFFBnpV/HWy8csMotMz7jru6f6fuR9ZKajkhpj3xmKgIb8zbbkz+wh9xMe4F1eXxRRjwvCSJpGzWW3GT8KhU5e1Y89K/kfRnVYRJAqGArzbHnxn8GjGz51cowslzjm3s6Vf34DDykrMsqkMF5dqwfwNFCagcECPSoBZzQhtRKmxnFLy/jt0vKB7R4/2OuVaJBFMTj7iu7YL24fQ7rTNaEUdqQOt7t7Z7GqyN6ITluxLZUZ/oP2BN9+/wo0QCNqNxxSm95XEOIGhH6YHbcoC0Za5X2WyEg5ZbSka09th4oYC9Zem9B5vDfRttHYOI5Uh1RhImXxPZy0YKV3xH7hC2vuGapYfjRJxgWBl4/j83Vks7T5JNwi2aK+qKGWm7kMSjYmelvOhL57AcC1jXIOwGS2bAfkh7L11PeVRoiyAhhsBZRIhTDQ5UUmdPJMYZtIBpdv3ogunFIoylrSJMlJ7U/P4HUVRktKvgDlChRE3F5VdxDRqclTiWxbC5bkre4MTIhN/GcZq6AvJzL6NYp/5Q1yLr+n8NM0CNRXxhFvOtpK+PkfUoZ8I5wwZdRP3vjhsWc1PDjxrPalR7kBUrxcpi36Xw5yq5bwm2cSEBl4js8LsWj7hTQXuwCGEbcvDE9jLIxDLmbhsILp1nlzJrsl66Xt/gZvvf1CAgqla0aJ6wuo=

provider:
  win: azure
